### PR TITLE
Get-PESymbols, Get-MethodAssembly and Get-MethodGraph

### PR DESCRIPTION
**Pull request by lowleveldesign**
I added a Get-PESymbols cmdlet to enable PDB symbols enumeration for PE files. I know it is almost only C# code, but I had problems with the enumeration callback in the `SymEnumSymbols` using PSReflect. The rest of the rules should be fulfilled. I decided to use the `_DBGHELP_PATH` variable to point to a specific dbghelp.dll - maybe you will have a better concept for that... 

Thanks!

### CODE REVIEW

**Comment by secabstraction** [comment]
If you're having trouble with the callback, checkout my blog post about Get-Keystrokes. I also have some code in my PowerWalker repo that enumerates symbols. http://www.patch-tuesday.net/2016/01/scripting-windows-key-logger.html

**Comment by lowleveldesign** [comment]
Thanks @secabstraction, I stumbled upon the original post by @mattifestation, but somehow forgot about it later. When I find a moment this week I will rewrite my script. 

I don't know how I missed PowerWalker when searching github - you put a lot of great code there. That would be another module of yours, after PowerCat, which I will be using :)

**Comment by lowleveldesign** [comment]
@secabstraction sounds good! I need to play with it a bit to learn the code. I suppose another way to get to managed stacks might be through .NET Rundown events (ASFAIK powerview does that). Maybe we should create an issue in PowerWalker repo and have the discussion there?

**Comment by lowleveldesign** [comment]
Ladies and Gentelmen, I've just committed pure-vanilla powershell-only Get-PESymbols :) I needed to slightly touch PSReflect module, but hopefully did not break anything.

**Pull request closed without merging**
